[[files]]
source = ".config/nvim/.gitignore"
target_linux = "/home/aw5qm/.config/nvim/.gitignore"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/.neoconf.json"
target_linux = "/home/aw5qm/.config/nvim/.neoconf.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/LICENSE"
target_linux = "/home/aw5qm/.config/nvim/LICENSE"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/README.md"
target_linux = "/home/aw5qm/.config/nvim/README.md"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/after/ftplugin/cpp.lua"
target_linux = "/home/aw5qm/.config/nvim/after/ftplugin/cpp.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/lua/config/conform.lua"
target_linux = "/home/aw5qm/.config/nvim/lua/config/conform.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/lua/config/lsp.lua"
target_linux = "/home/aw5qm/.config/nvim/lua/config/lsp.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/lua/plugins/typst.lua"
target_linux = "/home/aw5qm/.config/nvim/lua/plugins/typst.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/stylua.toml"
target_linux = "/home/aw5qm/.config/nvim/stylua.toml"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/colors/sigewinne-hydro.lua"
target_linux = "/home/aw5qm/.config/nvim/colors/sigewinne-hydro.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/nvim/init.lua"
target_linux = "/home/aw5qm/.config/nvim/init.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/wezterm/images/wallpaper.jpg"
target_linux = "/home/aw5qm/.config/wezterm/images/wallpaper.jpg"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/wezterm/wezterm.lua"
target_linux = "/home/aw5qm/.config/wezterm/wezterm.lua"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/ghostty/config"
target_linux = "/home/aw5qm/.config/ghostty/config"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/mise/config.toml"
target_linux = "/home/aw5qm/.config/mise/config.toml"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/tmux/.tmux.conf"
target_linux = "/home/aw5qm/.config/tmux/.tmux.conf"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/completions/fisher.fish"
target_linux = "/home/aw5qm/.config/fish/completions/fisher.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/completions/fzf_configure_bindings.fish"
target_linux = "/home/aw5qm/.config/fish/completions/fzf_configure_bindings.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/completions/mise.fish"
target_linux = "/home/aw5qm/.config/fish/completions/mise.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/completions/tailscale.fish"
target_linux = "/home/aw5qm/.config/fish/completions/tailscale.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/conf.d/fish_iceberg_theme.fish"
target_linux = "/home/aw5qm/.config/fish/conf.d/fish_iceberg_theme.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/conf.d/fzf.fish"
target_linux = "/home/aw5qm/.config/fish/conf.d/fzf.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/conf.d/z.fish"
target_linux = "/home/aw5qm/.config/fish/conf.d/z.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/__z.fish"
target_linux = "/home/aw5qm/.config/fish/functions/__z.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/__z_add.fish"
target_linux = "/home/aw5qm/.config/fish/functions/__z_add.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/__z_clean.fish"
target_linux = "/home/aw5qm/.config/fish/functions/__z_clean.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/__z_complete.fish"
target_linux = "/home/aw5qm/.config/fish/functions/__z_complete.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_configure_bindings_help.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_configure_bindings_help.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_extract_var_info.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_extract_var_info.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_preview_changed_file.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_preview_changed_file.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_preview_file.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_preview_file.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_report_diff_type.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_report_diff_type.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_report_file_type.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_report_file_type.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_directory.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_directory.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_git_log.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_git_log.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_git_status.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_git_status.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_history.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_history.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_processes.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_processes.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_search_variables.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_search_variables.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/_fzf_wrapper.fish"
target_linux = "/home/aw5qm/.config/fish/functions/_fzf_wrapper.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/fish_prompt.fish"
target_linux = "/home/aw5qm/.config/fish/functions/fish_prompt.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/fisher.fish"
target_linux = "/home/aw5qm/.config/fish/functions/fisher.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/fzf_configure_bindings.fish"
target_linux = "/home/aw5qm/.config/fish/functions/fzf_configure_bindings.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/functions/togglekey.fish"
target_linux = "/home/aw5qm/.config/fish/functions/togglekey.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/fish_plugins"
target_linux = "/home/aw5qm/.config/fish/fish_plugins"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/themes/fish_iceberg_theme.fish"
target_linux = "/home/aw5qm/.config/fish/themes/fish_iceberg_theme.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/config.fish"
target_linux = "/home/aw5qm/.config/fish/config.fish"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/fish/fish_variables"
target_linux = "/home/aw5qm/.config/fish/fish_variables"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/kanata/kanata.kbd"
target_linux = "/home/aw5qm/.config/kanata/kanata.kbd"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/lazygit/config.yml"
target_linux = "/home/aw5qm/.config/lazygit/config.yml"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zed/keymap.json"
target_linux = "/home/aw5qm/.config/zed/keymap.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zed/tasks.json"
target_linux = "/home/aw5qm/.config/zed/tasks.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zed/debug.json"
target_linux = "/home/aw5qm/.config/zed/debug.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zed/snippets/c++.json"
target_linux = "/home/aw5qm/.config/zed/snippets/c++.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zed/settings.json"
target_linux = "/home/aw5qm/.config/zed/settings.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zellij/config.kdl.bak"
target_linux = "/home/aw5qm/.config/zellij/config.kdl.bak"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".config/zellij/config.kdl"
target_linux = "/home/aw5qm/.config/zellij/config.kdl"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".claude/CLAUDE.md"
target_linux = "/home/aw5qm/.claude/CLAUDE.md"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".claude.json"
target_linux = "/home/aw5qm/.claude.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".claude/statusline.py"
target_linux = "/home/aw5qm/.claude/statusline.py"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".claude/settings.json"
target_linux = "/home/aw5qm/.claude/settings.json"
added_at = "2026-04-17T17:05:39"

[[files]]
source = ".zshrc"
target_linux = "/home/aw5qm/.zshrc"
added_at = "2026-04-17T17:11:05"

[[files]]
source = "nix-config/home/packages.nix"
target_linux = "/home/aw5qm/nix-config/home/packages.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/shell.nix"
target_linux = "/home/aw5qm/nix-config/home/shell.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/starship.nix"
target_linux = "/home/aw5qm/nix-config/home/starship.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/ssh.nix"
target_linux = "/home/aw5qm/nix-config/home/ssh.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/ghostty.nix"
target_linux = "/home/aw5qm/nix-config/home/ghostty.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/zellij.nix"
target_linux = "/home/aw5qm/nix-config/home/zellij.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/neovim.nix"
target_linux = "/home/aw5qm/nix-config/home/neovim.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/lazygit.nix"
target_linux = "/home/aw5qm/nix-config/home/lazygit.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/kanata.nix"
target_linux = "/home/aw5qm/nix-config/home/kanata.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/services.nix"
target_linux = "/home/aw5qm/nix-config/home/services.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/git.nix"
target_linux = "/home/aw5qm/nix-config/home/git.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/gtk.nix"
target_linux = "/home/aw5qm/nix-config/home/gtk.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/fonts.nix"
target_linux = "/home/aw5qm/nix-config/home/fonts.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/default.nix"
target_linux = "/home/aw5qm/nix-config/home/default.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/niri.nix"
target_linux = "/home/aw5qm/nix-config/home/niri.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/niri-minimal.nix"
target_linux = "/home/aw5qm/nix-config/home/niri-minimal.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/home/wsl.nix"
target_linux = "/home/aw5qm/nix-config/home/wsl.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/.gitignore"
target_linux = "/home/aw5qm/nix-config/configs/nvim/.gitignore"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/.neoconf.json"
target_linux = "/home/aw5qm/nix-config/configs/nvim/.neoconf.json"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/LICENSE"
target_linux = "/home/aw5qm/nix-config/configs/nvim/LICENSE"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/README.md"
target_linux = "/home/aw5qm/nix-config/configs/nvim/README.md"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/after/ftplugin/cpp.lua"
target_linux = "/home/aw5qm/nix-config/configs/nvim/after/ftplugin/cpp.lua"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/lua/config/lsp.lua"
target_linux = "/home/aw5qm/nix-config/configs/nvim/lua/config/lsp.lua"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/lua/plugins/typst.lua"
target_linux = "/home/aw5qm/nix-config/configs/nvim/lua/plugins/typst.lua"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/stylua.toml"
target_linux = "/home/aw5qm/nix-config/configs/nvim/stylua.toml"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/nvim/init.lua"
target_linux = "/home/aw5qm/nix-config/configs/nvim/init.lua"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/kanata/kanata.kbd"
target_linux = "/home/aw5qm/nix-config/configs/kanata/kanata.kbd"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/zellij/config.kdl"
target_linux = "/home/aw5qm/nix-config/configs/zellij/config.kdl"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/ghostty/config"
target_linux = "/home/aw5qm/nix-config/configs/ghostty/config"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/zed/settings.json"
target_linux = "/home/aw5qm/nix-config/configs/zed/settings.json"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/configs/zed/keymap.json"
target_linux = "/home/aw5qm/nix-config/configs/zed/keymap.json"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/.gitignore"
target_linux = "/home/aw5qm/nix-config/.gitignore"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/flake.lock"
target_linux = "/home/aw5qm/nix-config/flake.lock"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/vm-niri/niri.nix"
target_linux = "/home/aw5qm/nix-config/hosts/vm-niri/niri.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/vm-niri/hardware-configuration.nix"
target_linux = "/home/aw5qm/nix-config/hosts/vm-niri/hardware-configuration.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/vm-niri/configuration.nix"
target_linux = "/home/aw5qm/nix-config/hosts/vm-niri/configuration.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/usb-niri/niri.nix"
target_linux = "/home/aw5qm/nix-config/hosts/usb-niri/niri.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/usb-niri/configuration.nix"
target_linux = "/home/aw5qm/nix-config/hosts/usb-niri/configuration.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/usb-niri/hardware-configuration.nix"
target_linux = "/home/aw5qm/nix-config/hosts/usb-niri/hardware-configuration.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/hosts/wsl/configuration.nix"
target_linux = "/home/aw5qm/nix-config/hosts/wsl/configuration.nix"
added_at = "2026-04-17T17:12:13"

[[files]]
source = "nix-config/flake.nix"
target_linux = "/home/aw5qm/nix-config/flake.nix"
added_at = "2026-04-17T17:12:13"

[[ignores]]
kind = "name"
pattern = "settings.local.json"

[[ignores]]
kind = "name"
pattern = "/home/aw5qm/.claude.json"

[[ignores]]
kind = "name"
pattern = ".git/"

[[ignores]]
kind = "path"
pattern = "nix-config/.git/"
