[gd]
type = drive
client_id = 232151384040-do49kuk7iqmmhp6nrbte47hpmrna0duf.apps.googleusercontent.com
client_secret = GOCSPX-SkVw3DtB00gk2xDT9ayg1_GZgEN
scope = drive
service_account_file = ~/client_secret_232151384040-do49kuk7iqmmhp6nrbte47hpmrna0duf.apps.googleusercontent.com.json
team_drive = 

