
[tools]
"cargo:basalt-tui" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:kanata" = "latest"
bat = "latest"
chezmoi = "latest"
cmake = "latest"
direnv = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
yadm = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
